filegroup(
  name = 'Shared',
  srcs = ['source/BaseServer.mc',
          'source/CommunicationDelegate.mc',
          # 'source/FakeServer.mc',
          'source/Data.mc',
          'source/DateValue.mc',
          'source/DateValues.mc',
          'source/GlucoseServiceDelegate.mc',
          'source/GmwServer.mc',
          'source/ComServer.mc',
          'source/Log.mc',
          'source/Util.mc',
	 ],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Base',
  srcs = ['source/DeltaVarEncoder.mc',
         ],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Graph',
  srcs = ['source/DeltaVarEncoder.mc',
          'source/Graph.mc',
         ],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Arrays',
  srcs = ['source/Arrays.mc'],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Scheduler',
  srcs = ['source/BackgroundScheduler.mc'],
  visibility = ['//visibility:public'],
)
