filegroup(
  name = 'Shared',
  srcs = glob(['source/*.mc']),
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Resources',
  srcs = glob(['resources/**/*.xml']),
  visibility = ['//visibility:public'],
)


filegroup(
  name = 'Base',
  srcs = ['source/DeltaVarEncoder.mc',
         ],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Graph',
  srcs = ['source/DeltaVarEncoder.mc',
          'source/Graph.mc',
         ],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Arrays',
  srcs = ['source/Arrays.mc'],
  visibility = ['//visibility:public'],
)

filegroup(
  name = 'Scheduler',
  srcs = ['source/BackgroundScheduler.mc'],
  visibility = ['//visibility:public'],
)
